### ISSUE TITLE
Open Existing Template - Uncaught Type Error

### ISSUE THREAD

**Issue by justinyoo** [ytechie/AzureResourceVisualizer#14]
Hi, @ytechie 

Thanks for the awesome tool! Really appreciate it.

By the way, when I tried to load my existing ARM template, it gives me the error:

```
t.charAt is not a function
```

Here's my screenshot taken from Chrom Developer Tools.

![image](https://cloud.githubusercontent.com/assets/1538528/12933943/2b5e017a-cfdf-11e5-9540-dd7ad97519f0.png)

It would be great if you have a look at the function.

Cheers,

**Comment by ytechie** [comment]
Can you try running the template through this site? http://jsonlint.com/

That error is usually caused by something invalid like a stray comma.

**Comment by justinyoo** [comment]
Yep, I did try the JSON lint. It's valid. I can run my existing template to create resources anyway.

**Comment by ytechie** [comment]
Can you attach the template here?

**Comment by justinyoo** [comment]
Sure. Here's my gist:

https://gist.github.com/justinyoo/243b492f3ba6fb260468

**Comment by rchalumeau** [comment]
Hi @ytechie, 

I can reproduce the same issue and same traces with my template : https://gist.github.com/rchalumeau/55bbff57a89306e6c3d5

And by the way, thanks for your work
Romain

**Comment by msshli** [comment]
Hi @justinyoo @rchalumeau,

It seems that currently we are unable to resolve some of the names and dependencies in those templates. I have just added some code to ignore these cases, and you may still edit them.

**Comment by msshli** [comment]
Fixed this bug.
