### ISSUE TITLE
ServiceBus template visualizer fails

### ISSUE THREAD

**Issue by sazeesha** [ytechie/AzureResourceVisualizer#15]
The Visualize Button for ServiceBus template does not show the right visualization.
https://github.com/Azure/azure-quickstart-templates/tree/master/servicebus-pn-ar

What does it take to have the correct visualization for ServiceBus Provider

**Comment by ytechie** [comment]
That link isn't working, so I can't take a look at the exact problem. The URL of the template to render gets passed in the URL in the "load" parameter. Confirm that is correct. If you're in a branch, it will probably be wrong until it's merged.

**Comment by sazeesha** [comment]
Here is the right link, I removed the Visualize button as it was broken https://github.com/Azure/azure-quickstart-templates/tree/master/101-servicebus-pn-ar
