### ISSUE TITLE
.github shown in contents list during load templates

### ISSUE THREAD

**Issue by sudheesh001** [ytechie/AzureResourceVisualizer#20]
In the load Quick start templates select option in modals, the .github file is visible whereas it shouldn't be visible. It looks like the condition for `.github` isn't added yet, it needs to be an (or) condition along with the current condition present here. 

https://github.com/ytechie/AzureResourceVisualizer/blob/85d737a0db863ee2d6ad96aeec4d0a7f9f64b51a/src/app/quickstartLoadDialog/GithubTemplateReader.ts#L20

**Comment by ytechie** [comment]
I confirmed this has been fixed and deployed.
