### ISSUE TITLE
Error loading your template from GitHub

### ISSUE THREAD

**Issue by eisber** [ytechie/AzureResourceVisualizer#23]
I get "Error loading your template from GitHub" message when trying to visualize our ARM template: https://github.com/multiworldtesting/ds-provisioning
Any error details?

**Comment by ytechie** [comment]
Can you try it again? It's working here. I want to make sure it's not a throttling issue.

**Comment by eisber** [comment]
Works now. Thanks!

**Comment by ytechie** [comment]
Thank you. Good for you, bad for us!
