### ISSUE TITLE
[Enhancement] - Support multiple tabs

### ISSUE THREAD

**Issue by bcraun** [ytechie/AzureResourceVisualizer#24]
It would be nice to be able to work with multiple ARM templates simultaneously. Idea would be to use a convention similar to most browsers where a "+" button is used to spawn a new visualizer tab. The new visualizer tab would default to empty, but have same functionality as the others. An "X" button would destroy the visualizer tab.

**Comment by ytechie** [comment]
Interesting idea. Calling @msshli for his thoughts. We are working on a new UI layout, but I'm not quite sure if I see the value in tabs.

Why not just open the tabs in your browser?

**Comment by bcraun** [comment]
Yeah multiple tabs in browser works too. Go ahead and close my request if you want. Separate browser tabs accomplishes the same thing albeit with a few more cycles.

On Fri, Jul 15, 2016 at 6:07 PM -0400, "Jason Young" notifications@github.com wrote:

Interesting idea. Calling @msshli for his thoughts. We are working on a new UI layout, but I'm not quite sure if I see the value in tabs.

Why not just open the tabs in your browser?

**Comment by ytechie** [comment]
In any case, thanks for reaching out!
