### ISSUE TITLE
Quickstart template loader not working

### ISSUE THREAD

**Issue by DarylsCorner** [ytechie/AzureResourceVisualizer#4]
Unable to load any Quickstart templates.

**Comment by ytechie** [comment]
What browser are you using? It's working here. If it's IE11, that's a known issue.

**Comment by DarylsCorner** [comment]
Yep, I'm using IE11. I tried in chrome and it's fine. Thanks.

**Comment by DarylsCorner** [comment]
By the way, great job on this project. Just blogged about it today at darylscorner.com and gave you a shout out.

**Comment by ytechie** [comment]
Awesome, I'll tweet it!
