### ISSUE TITLE
DependsOn Not Working on mysql Template

### ISSUE THREAD

**Issue by ytechie** [ytechie/AzureResourceVisualizer#5]
http://armviz.io/#/?load=https:%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%2Fmysql-replication%2Fazuredeploy.json

I don’t see how this is supposed to work. This doesn’t make sense:
This is the “dependsOn” value:
[concat('Microsoft.Network/networkInterfaces/', variables('nicName'), copyIndex())]
 
I assume it’s support to reference this resource:
"name": "[concat(variables('nicName'), copyIndex())]"
 
I’ve never seen that particular syntax being used, and I don’t support it.

**Comment by brentstineman** [comment]
Looks like this may be resolved now. Not sure if this is directly due to PR#7 or now.

**Comment by ytechie** [comment]
It is fixed. Thanks!
